dist: trusty
sudo: false
language: cpp

branches:
  only:
    - master
    - /^release\/\d+\.x$/
    - coverity_scan

env:
  global:
    - LOCAL_INSTALLS="$HOME/local-installs"
    - CORES=2
    - CLANG_FORMAT_DIFF="clang-format-diff-4.0"

    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created via
    # the "travis encrypt" command using the project repo's public key
    - secure: "GkEHjN/3Ir8eo9kJNJ0xxCWvc1sh5OaKtQ9gpehW54Pik/rRqBAoyNJGcmkUntx/PaePJBwf+w+SFP71426TymvNjOA/K4uvtP9cIgMW9E9mxwwr5CmpuG8UVcisPEnntySR5ljQ5heqdM6+4uR0NC8GGaONCM3JYsdXuyVe3kz0HGra7A8NA/8kplbgul53+WJWkG82rEUjAkVBs+6HquBhDxrddWbzjurk7K8yNvCHuUYwIaryCsGmbUF7om4dXZtRqoFARkevJnGd51vbDxdzvwbPpkkDFFtyd4vuJrMxgAd6S71m0uemI+B8qIuhhL1BH7C82teyymLhSVB9q0DIfqCpC71mgdptb3298Z9ItPaceT+licjJ19vvAUtj7MoFbtszZy78uyrmGjg/w140YiJ40TKZjpz9Qlnr8LFS++wqkFWIvsr4aZOrdMOFMzowY/g5Ffe0/35ph8AXRYIhKXYewNZI786EpZtc4Rd45PWJ4UyFOeCTBvIXfp1ApyCx+ScemHe/B70vSBHSsJMA23+TBHP4Uj5CsRrLnrCx2aommuRKY2cAqcQXzdVw6ga2G9+S1Bg+CR3Om8L7frR/j/2zhZyPfwK/sB0oDdpeyyFv/zMUy3HPlWjwQyKfiPmd1D7wiEcwDf1uYVbYvTwOwyvH3FGehvPiXONadK4="

matrix:
  fast_finish: true
  include:
    # normal
    # gpg stable
    - env: BUILD_MODE=normal GPG_VERSION=stable
      compiler: clang
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=normal GPG_VERSION=stable
      compiler: clang
      stage: test
    # gpg master
    - env: BUILD_MODE=normal GPG_VERSION=beta
      compiler: clang
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=normal GPG_VERSION=beta
      compiler: clang
      stage: test
    # normal (macos)
    # gpg stable
    - env: BUILD_MODE=normal GPG_VERSION=stable
      os: osx
      osx_image: xcode10.1
      compiler: clang
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=normal GPG_VERSION=stable
      os: osx
      osx_image: xcode10.1
      compiler: clang
      stage: test

    # clang sanitizers
    # gpg stable
    - env: BUILD_MODE=sanitize GPG_VERSION=stable
      compiler: clang
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=sanitize GPG_VERSION=stable
      compiler: clang
      sudo: true
      stage: test
    # gpg master
    - env: BUILD_MODE=sanitize GPG_VERSION=beta
      compiler: clang
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=sanitize GPG_VERSION=beta
      compiler: clang
      sudo: true
      stage: test

    # codecov
    - env: BUILD_MODE=coverage RNP_TESTS=rnp_tests GPG_VERSION=beta
      compiler: gcc
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=coverage RNP_TESTS=rnp_tests GPG_VERSION=beta
      compiler: gcc
      stage: test
    - env: BUILD_MODE=coverage RNP_TESTS=cli_tests GPG_VERSION=beta
      compiler: gcc
      stage: cache
      before_install: true
      script: true
    - env: BUILD_MODE=coverage RNP_TESTS=cli_tests GPG_VERSION=beta
      compiler: gcc
      stage: test

    # clang-format style checks
    - env: BUILD_MODE=style-check
      install: true
      script: ci/style-check.sh
      stage: test
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-format-4.0

  allow_failures:
    # allowed to fail until we have stabilized on a clang-format version
    - env: BUILD_MODE=style-check
      install: true
      stage: test

stages:
  - cache
  - test

cache:
  directories:
    - "$LOCAL_INSTALLS"

before_install:
  - . ci/env.inc.sh
  - ./ci/before_install.sh
  - rvm use 2.4.6 --install --binary

install:
  - . ci/env.inc.sh
  - travis_wait 50 ./ci/install.sh

script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then travis_wait 50 ./ci/main.sh; fi

after_success:
  - ./ci/success.sh

addons:
  homebrew:
    brewfile: true

  coverity_scan:

    # GitHub project metadata
    # ** specific to your project **
    project:
      name: "riboseinc/rnp"
      description: "The rnp OpenPGP implementation"
      # version: 1.0

    # Where email notification of build analysis results will be sent
    notification_email: packaging@ribose.com

    # Commands to prepare for build_command
    # ** likely specific to your build **
    build_command_prepend: ""

    # The command that will be added as an argument to "cov-build" to compile
    # your project for analysis,
    # ** likely specific to your build **
    build_command: "./ci/main.sh"

    # Pattern to match selecting branches that will run analysis. We recommend
    # leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan

